import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/Navbar";
import { auth0 } from "@/lib/auth";
import { Suspense } from "react";
import Footer from "@/components/layout/Footer";
const robotoHeading = Roboto({
  subsets: ["latin"],
  variable: "--font-heading",
});

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //fetch session on the server - passes user to Navbar
  const session = await auth0.getSession();
  const user = session?.user ?? null;
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
        robotoHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={null}>
          <Navbar user={user} />
        </Suspense>
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
